PICO split and merge
pism/pism pull request #481
Opened 2021-04-12 08:33 UTC by talbrecht

This pull request adds some special treatment of ice shelves and ocean inputs in the **PICO** ocean module (e.g. in case of a collapse of the West Antarctic Ice Sheet). When ice shelves merge across basin boundaries that both have access to the ocean, but that do not share a common ocean boundary (no basin neighbors at the coast), then those ice shelves are split into two separate instances with individual ocean inputs. When a grounding line retreats into another basins, which does not has a connection to the ocean in that basin (ice shelf cavity), ocean conditions from this basin are not considered in the area-weighted average of the ocean inputs for this ice shelf instance.

**Checklist**

- [x ] update documentation
- [x ] update [`CHANGES.rst`](CHANGES.rst)
- [x ] add regression tests

2021-06-02 02:03 UTC, ckhroulev requested changes
Looks good, but needs a bit of tidying up. Thanks!

2021-06-02 02:03 UTC, ckhroulev commented on src/coupler/ocean/PicoGeometry.cc
> +    //GlobalSum(m_grid->com, n_shelf_cells_per_basin.data(), m_n_shelves*m_n_basins);
Please remove commented out code to reduce clutter.

2021-06-02 02:03 UTC, ckhroulev commented on src/coupler/ocean/PicoGeometry.cc
> +  //GlobalSum(m_grid->com, n_shelf_cells_to_split.data(), m_n_shelves*m_n_basins);
Please remove commented out code to reduce clutter.

2021-06-02 02:03 UTC, ckhroulev commented on test/test_pico_split/run_test.sh
> +#           input_test01.nc
Here and below: please remove commented out code to reduce clutter.

2021-06-02 02:03 UTC, ckhroulev commented on src/coupler/ocean/Pico.cc
> +        //}
Please remove commented out code to reduce clutter.

2021-06-18 13:12 UTC, talbrecht commented on src/coupler/ocean/Pico.cc
> +        //}
Oops, I guess I rebased merge_pico instead of pico_merge... Will update this one later...

2021-06-19 13:36 UTC, talbrecht commented
OK, pik/pico_merge is now rebased to dev, cleaned up old comments, and GlobalSums reformulated for better performance. The test_pico_split has been updated...

2021-06-21 20:09 UTC, ckhroulev commented
The current version looks good to me. @talbrecht, please run a couple of tests to check that it still works the way you intended.

And one more thing: we need to automate the regression test. The shell script should return 0 on success and something else (1, for example) on failure (just add `exit 0` and `exit 1` in the right places).

2021-06-22 08:20 UTC, talbrecht commented
A added a lot of `if` and `else`, but it seems to work as a quick regression test... I guess the `echo`s could be removed then?

2021-06-22 15:12 UTC, ckhroulev commented
> I guess the echos could be removed then?

They aren't hurting anything, so I'd leave it like this.

Thanks!

2021-06-22 20:00 UTC, talbrecht commented
The regression test works fine... Always good to learn some more bash...

2021-06-22 20:03 UTC, merged